services:
  - type: web
    name: paco-api
    runtime: python
    region: oregon
    plan: free
    branch: main
    rootDir: paco-api
    buildCommand: "./build.sh"
    startCommand: "./start_render.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DATABASE_URL
        fromDatabase:
          name: paco-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: GROQ_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: ELEVENLABS_AGENT_ID
        sync: false

databases:
  - name: paco-db
    databaseName: paco
    plan: free
    region: oregon
